routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test', 'PageController@getTest')->name('test');

Route::get('/', 'PageController@getHome')->name('homePage');
Route::post('/newsletter', 'PageController@storeNewsletter')->name('newsletter');

Route::get('/help', 'PageController@getHowTo')->name('howToPage');
Route::get('/productShop/{tag?}', 'PageController@getProducts')->name('productsPage');
Route::get('/about', 'PageController@getAbout')->name('aboutPage');
Route::get('/terms', 'PageController@getTerms')->name('termsPage');
Route::get('/policy', 'PageController@getPolicy')->name('policyPage');

//Route::get('/contact', 'PageController@getContact')->name('contactPage');
Route::get('contact', 'ContactController@show')->name('contact.show');
Route::post('contact','ContactController@create')->name('contact.create');

Route::get('/profile/{user}', 'UserProfileController@showProfile')->name('user.profile');
Route::put('/profile/{user}', 'UserProfileController@updateUserProfile')->name('user.profile.update');
Route::put('/profileaddress/{user}', 'UserProfileController@updateUserAddress')->name('user.address.update');
Route::put('/profilepassword/{user}', 'UserProfileController@updateUserPassword')->name('user.password.update');

Route::get('/orderHistory', 'OrderController@index')->name('order.index');
Route::post('/order', 'OrderController@store')->name('order.store');

//socialite routes
//Route::get('login/google', 'Auth\LoginController@redirectToProvider')->name('googleLogin');
//Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/editor/{product?}', 'PageController@editor')->name('editorPage');
Route::get('searchResult', 'PageController@getSearchProduct')->name('productSearch');
Route::post('/preview', 'PageController@editorPreview')->name('editorPreview');

Route::middleware('role:admin')->prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/dashboard', 'AdminController@getDashboard')->name('admin.dashboard');

        Route::resource('categories', 'CategoryController');
        Route::resource('tags', 'TagController');
        Route::resource('products', 'ProductController');
        Route::resource('templateImages', 'TemplateImageController');

        Route::get('/orders', 'AdminOrderController@getOrders')->name('admin.orders');
        Route::get('/orders/{customerOrder}', 'AdminOrderController@updateOrderStatus')->name('admin.orders.update');
        Route::get('/items/{customerOrder}', 'AdminOrderController@viewOrderItems')->name('admin.order.items');

        Route::get('/featured', 'PageController@getFeaturedProduct')->name('featured.product');
        Route::get('/featured/{product}', 'PageController@removeFeaturedProduct')->name('update.featured.product');
    });
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/myCart', 'CartController@index')->name('cart.index');
    Route::post('/myCart/{product}', 'CartController@store')->name('cart.store');
    Route::delete('/myCart/{cartitem}', 'CartController@delete')->name('cart.destroy');
    Route::put('/myCart/{cartitem}', 'CartController@update')->name('cart.update');
});

resources/views/admin/template/index.blade.php
@extends('admin.layout.app')
@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Template Image</h1>
        <button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#addTemplateImage">
            <i class="fas fa-plus mr-2"></i>
            Add Template
        </button>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                @if(count($errors)>0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover">
                        <thead class="thead-dark">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($templateimages as $templateimage)
                            <tr>
                                <td class="align-middle">{{ $templateimage->id }}</td>
                                <td class="align-middle">{{ $templateimage->name }}</td>
                                <td>
                                    <img src="{{asset($templateimage->image->url)}}" height="100px">
                                </td>
                                <td class="align-middle">
                                    {{ Form::open(['route' => ['templateImages.destroy', $templateimage->id], 'method' => 'DELETE']) }}
                                    {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="addTemplateImage" role="dialog">
        <div class="modal-dialog modal-sm">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Template Image</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    {!! Form::open(['url' => route('templateImages.store'),'method'=>'POST','enctype'=>'multipart/form-data']) !!}
                    {{ Form::label('name', 'Name:') }}
                    {{ Form::text('name', null, ['class' => 'form-control']) }}
                    <label for="template_image">Template Image</label>
                    <input type="file" class="form-control" name="template_image">
                    {{ Form::submit('Add Template Image', ['class' => 'btn btn-primary btn-block mt-4']) }}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection