routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test', 'PageController@getTest')->name('test');

Route::get('/', 'PageController@getHome')->name('homePage');
Route::post('/newsletter', 'PageController@storeNewsletter')->name('newsletter');

Route::get('/help', 'PageController@getHowTo')->name('howToPage');
Route::get('/productShop/{tag?}', 'PageController@getProducts')->name('productsPage');
Route::get('/about', 'PageController@getAbout')->name('aboutPage');
Route::get('/terms', 'PageController@getTerms')->name('termsPage');
Route::get('/policy', 'PageController@getPolicy')->name('policyPage');

//Route::get('/contact', 'PageController@getContact')->name('contactPage');
Route::get('contact', 'ContactController@show')->name('contact.show');
Route::post('contact','ContactController@create')->name('contact.create');

Route::get('/profile/{user}', 'UserProfileController@showProfile')->name('user.profile');
Route::put('/profile/{user}', 'UserProfileController@updateUserProfile')->name('user.profile.update');
Route::put('/profileaddress/{user}', 'UserProfileController@updateUserAddress')->name('user.address.update');
Route::put('/profilepassword/{user}', 'UserProfileController@updateUserPassword')->name('user.password.update');

Route::get('/orderHistory', 'OrderController@index')->name('order.index');
Route::post('/order', 'OrderController@store')->name('order.store');

//socialite routes
//Route::get('login/google', 'Auth\LoginController@redirectToProvider')->name('googleLogin');
//Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/editor/{product?}', 'PageController@editor')->name('editorPage');
Route::get('searchResult', 'PageController@getSearchProduct')->name('productSearch');
Route::post('/preview', 'PageController@editorPreview')->name('editorPreview');

Route::middleware('role:admin')->prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/dashboard', 'AdminController@getDashboard')->name('admin.dashboard');

        Route::resource('categories', 'CategoryController');
        Route::resource('tags', 'TagController');
        Route::resource('products', 'ProductController');
        Route::resource('templateImages', 'TemplateImageController');

        Route::get('/orders', 'AdminOrderController@getOrders')->name('admin.orders');
        Route::get('/orders/{customerOrder}', 'AdminOrderController@updateOrderStatus')->name('admin.orders.update');
        Route::get('/items/{customerOrder}', 'AdminOrderController@viewOrderItems')->name('admin.order.items');

        Route::get('/featured', 'PageController@getFeaturedProduct')->name('featured.product');
        Route::get('/featured/{product}', 'PageController@removeFeaturedProduct')->name('update.featured.product');
    });
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/myCart', 'CartController@index')->name('cart.index');
    Route::post('/myCart/{product}', 'CartController@store')->name('cart.store');
    Route::delete('/myCart/{cartitem}', 'CartController@delete')->name('cart.destroy');
    Route::put('/myCart/{cartitem}', 'CartController@update')->name('cart.update');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table='products';
    protected $fillable = [
        'product_code','name', 'featured_product', 'price', 'discount', 'category_id', 'slug', 'data',
    ];

    public function getRouteKeyName()
    {
        return 'product_code';
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
    public function orderItems()
    {
        return $this->hasMany(OrderItem::class, 'product_id');
    }

    public function scopeSearch($query,$search){
        return $query->where('name','like','%'.$search.'%');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\StoreProduct;
use App\Http\Requests\UpdateProduct;
use App\Product;
use App\Tag;
use App\TemplateImage;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('admin.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        $templates = TemplateImage::all();
        $templateArray = array();
        foreach ($templates as $template) {
//            $templateArray[$template->name] = $template->image->url;
            array_push($templateArray, asset($template->image->url));
        }
        return view('admin.product.create', compact('categories', 'tags', 'templates', 'templateArray'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProduct $request)
    {
        //First Product Image
        $firstFile = $request->file('first_image');
        $firstFilenameWithExt = $firstFile->getClientOriginalName();
        $firstFilename = pathinfo($firstFilenameWithExt, PATHINFO_FILENAME);
        $extension = $firstFile->getClientOriginalExtension();
        $firstFileNameToStore= $firstFilename.'_'.time().'.'.$extension;

        //Second Product Image
        $secondFile = $request->file('second_image');
        $secondFilenameWithExt = $secondFile->getClientOriginalName();
        $secondFilename = pathinfo($secondFilenameWithExt, PATHINFO_FILENAME);
        $extension = $secondFile->getClientOriginalExtension();
        $secondFileNameToStore= $secondFilename.'_'.time().'.'.$extension;

        //Third Product Image
        $thirdFile = $request->file('third_image');
        $thirdFilenameWithExt = $thirdFile->getClientOriginalName();
        $thirdFilename = pathinfo($thirdFilenameWithExt, PATHINFO_FILENAME);
        $extension = $thirdFile->getClientOriginalExtension();
        $thirdFileNameToStore= $thirdFilename.'_'.time().'.'.$extension;

        $firstimagedata = [
            'image' => $firstFilename,
            'path' => $firstFile->storeAs('product', $firstFileNameToStore, 'public'),
            'meta' => 'first_image',
        ];
        $secondimagedata = [
            'image' => $secondFilename,
            'path' => $secondFile->storeAs('product', $secondFileNameToStore, 'public'),
            'meta' => 'second_image',
        ];
        $thirdimagedata = [
            'image' => $thirdFilename,
            'path' => $thirdFile->storeAs('product', $thirdFileNameToStore, 'public'),
            'meta' => 'third_image',
        ];

    $productdata = [
        'product_code' => $request->get('product_code'),
        'name' => $request->get('name'),
        'featured_product'=>$request->has('featured_product') ? true:false,
        'price' => $request->get('price'),
        'discount' => $request->get('discount'),
        'category_id' => $request->get('category_id'),
        'slug' => str_slug($request->get('product_code')),
        'data' => $request->get('data'),
    ];

        $p = Product::create($productdata);
        $p->image()->create($firstimagedata);
        $p->image()->create($secondimagedata);
        $p->image()->create($thirdimagedata);
        $p->tags()->sync($request->get('tags'));
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Product $movie
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        $selectedcategory = array();
        foreach ($categories as $category) {
            $selectedcategory[$category->id] = $category->name;
        }

        $tags = Tag::all();
        $selectedtag = array();
        foreach ($tags as $tag) {
            $selectedtag[$tag->id] = $tag->name;
        }

        return view('admin.product.edit', compact('product','selectedcategory','selectedtag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateMovie $request
     * @param Product $movie
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProduct $request, Product $product)
    {
        $productdata=[
            'product_code'=>$request->get('product_code'),
            'featured_product'=>$request->has('featured_product') ? true:false,
            'name'=>$request->get('name'),
            'price'=>$request->get('price'),
            'discount'=>$request->get('discount'),
            'slug'=>str_slug($request->get('product_code')),
            'category_id' => $request->get('category_id'),
        ];
        $product->update($productdata);

        if (isset($request->tags)) {
            $product->tags()->sync($request->tags);
        } else {
            $product->tags()->sync(array());
        }

        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product =Product::find($id);
        $product->image()->delete();
        $product->tags()->detach();
        $product->delete();

        return redirect()->route('products.index');
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layout.app')
@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Add Product</h1>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {{--{{ dd($templates) }}--}}
                {{--@foreach($templates as $template)--}}
                    {{--<img src="{{asset($template->image->url)}}">--}}
                {{--@endforeach--}}
                @if(count($errors)>0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                {!! Form::open(['url' => route('products.store'),'method'=>'POST','enctype'=>'multipart/form-data', 'class'=>'mb-5']) !!}
                <div class="col-sm-12">
                    <label for="product_code">Product Code</label>
                    <input type="text" class="form-control" name="product_code">
                </div>
                <div class="col-sm-12">
                    <label for="name">Product Name</label>
                    <input type="text" class="form-control" name="name">
                </div>
                <div class="col-sm-12">
                    <input type="checkbox" name="featured_product" value="1"><br>
                    <label for="featured_product d-inline-block">Feature this Product</label>
                </div>
                <div class="col-sm-12">
                    <label for="price">Price</label>
                    <input type="text" class="form-control" name="price">
                </div>
                <div class="col-sm-12">
                    <label for="discount">Discount</label>
                    <input type="text" class="form-control" name="discount">
                </div>
                <div class="col-sm-12">
                    <label for="category_id">Product Category</label>
                    <select class="form-control" name="category_id">
                        @foreach($categories as $category)
                            <option value='{{ $category->id }}'>{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-sm-12">
                    <label for="tags[]">Tag</label>
                    <select class="form-control select2-multi" name="tags[]" multiple="multiple">
                        @foreach($tags as $tag)
                            <option value='{{ $tag->id }}'>{{ $tag->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-sm-12">
                    <label for="first_image">First Image</label>
                    <input type="file" class="form-control" name="first_image">
                </div>
                <div class="col-sm-12">
                    <label for="second_image">Second Image</label>
                    <input type="file" class="form-control" name="second_image">
                </div>
                <div class="col-sm-12">
                    <label for="third_image">Third Image</label>
                    <input type="file" class="form-control" name="third_image">
                </div>

                <div class="col-sm-12">
                    {{--<label for="data">Product Data</label>--}}
                    {{--<textarea class="form-control" name="data"></textarea>--}}

                    <div id="app">
                        <admin-editor></admin-editor>
                        {{--<admin-editor images="{!! json_encode($templateArray) !!}"></admin-editor>--}}
                    </div>
                </div>

                <br><br>
                {{Form::submit('Submit',['class'=>'btn btn-primary'])}}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

@push('stylesheet')
    <link rel="stylesheet" href="{{ asset('css/editor-style.css') }}">
    {!! Html::style('css/select2.min.css')!!}
@endpush
@push('scripts')
    <script>
        var images = JSON.parse("{!! addslashes(json_encode($templateArray)) !!}");
    </script>
    <script src="{{ asset('js/fabric.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    {!! Html::script('js/select2.min.js')!!}

    <script type="text/javascript">
        $(document).ready(function () {
            $('.select2-multi').select2();
        });
    </script>
@endpush

resources/views/admin/product/edit.blade.php
@extends('admin.layout.app')
@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Edit Product</h1>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {{ Form::model($product,['url' => route( 'products.update',$product->product_code),'method'=>'PUT','enctype'=>'multipart/form-data']) }}

                {{--{{ Form::model($category, ['route' => ['categories.update', $category->slug], 'method' => "PUT"]) }}--}}
                {{--{{dd($movie)}}--}}
                <div class="col-sm-12">
                    {{ Form::label('product_code', 'Product Code') }}
                    {{ Form::text('product_code', null, ["class" => 'form-control']) }}
                </div>
                <div class="col-sm-12">
                    {{ Form::label('name', 'Product Name') }}
                    {{ Form::text('name', null, ["class" => 'form-control']) }}
                </div>
                <div class="col-sm-12">
                    {{ Form::label('featured_product', 'Feature this Product') }}
                    {{ Form::checkbox('featured_product','1',null, ["class" => 'form-control']) }}
                    {{--<label for="feature_movie">Feature this Movie</label>--}}
                    {{--<input type="checkbox" name="feature_movie" value="1"><br>--}}
                </div>

                <div class="col-sm-12">
                    {{ Form::label('price', 'Price') }}
                    {{ Form::text('price', null, ["class" => 'form-control']) }}
                </div>

                <div class="col-sm-12">
                    {{ Form::label('discount', 'Discount') }}
                    {{ Form::text('discount', null, ["class" => 'form-control']) }}
                </div>

                <div class="col-sm-12">
                    {{ Form::label('category_id', 'Product Category') }}
                    {{ Form::select('category_id', $selectedcategory, null, ['class' => 'form-control']) }}
                </div>
                <div class="col-sm-12">
                    {{ Form::label('tags', 'Tags') }}
                    {{ Form::select('tags[]', $selectedtag, null, ['class' => 'form-control select2-multi', 'multiple' => 'multiple']) }}
                </div>

                {{--<div class="col-sm-12">--}}
                    {{--{{ Form::label('first_image', 'First Image') }}--}}
                    {{--{{ Form::file('first_image', null, ["class" => 'form-control']) }}--}}
                {{--</div>--}}

                {{--<div class="col-sm-12">--}}
                    {{--{{ Form::label('second_image', 'Second Image') }}--}}
                    {{--{{ Form::file('second_image', null, ["class" => 'form-control']) }}--}}
                {{--</div>--}}

                {{--<div class="col-sm-12">--}}
                    {{--{{ Form::label('third_image', 'Third Image') }}--}}
                    {{--{{ Form::file('third_image', null, ["class" => 'form-control']) }}--}}
                {{--</div>--}}

                {{Form::submit('Submit',['class'=>'btn btn-primary'])}}
                {!! Form::close() !!}

            </div>
        </div>
    </div>
@endsection

@push('stylesheet')
    <link rel="stylesheet" href="{{ asset('css/editor-style.css') }}">
    {!! Html::style('css/select2.min.css')!!}
@endpush
@push('scripts')
    <script src="{{ asset('js/fabric.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    {!! Html::script('js/select2.min.js')!!}

    <script type="text/javascript">
        $(document).ready(function () {
            $('.select2-multi').select2();
        });
    </script>
@endpush

resources/views/admin/product/index.blade.php
@extends('admin.layout.app')
@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Product</h1>
        <a href="{{route('products.create')}}">
            <button type="button" class="btn btn-info pull-right">
                <i class="fas fa-plus mr-2"></i>
                Add Product
            </button>
        </a>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover">
                        <thead class="thead-dark">
                        <tr>
                            <th>Product Code</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($products as $product)
                            <tr>
                                <td class="align-middle">{{ $product->product_code }}</td>
                                <td class="align-middle">{{ $product->name }}</td>
                                <td class="align-middle">
                                    <img src="{{asset($product->image->url)}}" height="150px">
                                </td>

                                <td class="align-middle">
                                    <a href="{{route('products.edit',$product->product_code)}}" type="button" class="btn btn-primary mr-3 d-inline-block">Edit</a>

                                    {{ Form::open(['route' => ['products.destroy', $product->id], 'method' => 'DELETE', 'class'=>'d-inline-block']) }}
                                    {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                                    {{ Form::close() }}

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection