routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test', 'PageController@getTest')->name('test');

Route::get('/', 'PageController@getHome')->name('homePage');
Route::post('/newsletter', 'PageController@storeNewsletter')->name('newsletter');

Route::get('/help', 'PageController@getHowTo')->name('howToPage');
Route::get('/productShop/{tag?}', 'PageController@getProducts')->name('productsPage');
Route::get('/about', 'PageController@getAbout')->name('aboutPage');
Route::get('/terms', 'PageController@getTerms')->name('termsPage');
Route::get('/policy', 'PageController@getPolicy')->name('policyPage');

//Route::get('/contact', 'PageController@getContact')->name('contactPage');
Route::get('contact', 'ContactController@show')->name('contact.show');
Route::post('contact','ContactController@create')->name('contact.create');

Route::get('/profile/{user}', 'UserProfileController@showProfile')->name('user.profile');
Route::put('/profile/{user}', 'UserProfileController@updateUserProfile')->name('user.profile.update');
Route::put('/profileaddress/{user}', 'UserProfileController@updateUserAddress')->name('user.address.update');
Route::put('/profilepassword/{user}', 'UserProfileController@updateUserPassword')->name('user.password.update');

Route::get('/orderHistory', 'OrderController@index')->name('order.index');
Route::post('/order', 'OrderController@store')->name('order.store');

//socialite routes
//Route::get('login/google', 'Auth\LoginController@redirectToProvider')->name('googleLogin');
//Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/editor/{product?}', 'PageController@editor')->name('editorPage');
Route::get('searchResult', 'PageController@getSearchProduct')->name('productSearch');
Route::post('/preview', 'PageController@editorPreview')->name('editorPreview');

Route::middleware('role:admin')->prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/dashboard', 'AdminController@getDashboard')->name('admin.dashboard');

        Route::resource('categories', 'CategoryController');
        Route::resource('tags', 'TagController');
        Route::resource('products', 'ProductController');
        Route::resource('templateImages', 'TemplateImageController');

        Route::get('/orders', 'AdminOrderController@getOrders')->name('admin.orders');
        Route::get('/orders/{customerOrder}', 'AdminOrderController@updateOrderStatus')->name('admin.orders.update');
        Route::get('/items/{customerOrder}', 'AdminOrderController@viewOrderItems')->name('admin.order.items');

        Route::get('/featured', 'PageController@getFeaturedProduct')->name('featured.product');
        Route::get('/featured/{product}', 'PageController@removeFeaturedProduct')->name('update.featured.product');
    });
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/myCart', 'CartController@index')->name('cart.index');
    Route::post('/myCart/{product}', 'CartController@store')->name('cart.store');
    Route::delete('/myCart/{cartitem}', 'CartController@delete')->name('cart.destroy');
    Route::put('/myCart/{cartitem}', 'CartController@update')->name('cart.update');
});

resources/views/admin/partial/_footer.blade.php
<footer class="footer">
<div class="container-fluid">
    <nav class="pull-left">
        <ul>
            <li>
                <a href="#">
                    Home
                </a>
            </li>
            <li>
                <a href="#">
                    Company
                </a>
            </li>
            <li>
                <a href="#">
                    Portfolio
                </a>
            </li>
            <li>
                <a href="#">
                    Blog
                </a>
            </li>
        </ul>
    </nav>
    <p class="copyright pull-right">
        &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
    </p>
</div>
</footer>

resources/views/admin/partial/_head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    {{--<!-- Bootstrap core CSS -->--}}
    {{--<link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">--}}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{asset('css/fontawesome-all.css')}}">
    <!-- Custom styles for this template -->
    <link href="{{asset('css/dashboard-style.css')}}" rel="stylesheet"/>
    @stack('stylesheet')

</head>

resources/views/admin/partial/_navigation.blade.php
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{ route('homePage') }}">Lambada</a>
    {{--<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">--}}
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            {{--<a class="nav-link" href="#">Sign out</a>--}}
            <a class="nav-link" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                Sign out
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                  style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
</nav>

resources/views/admin/partial/_script.blade.php
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{{--Icon--}}
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()

</script>

@stack('scripts')

resources/views/admin/partial/_sidebar.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/dashboard') ? "active" : "" }}" href="{{route('admin.dashboard')}}">
                    <span data-feather="layout"></span>
                    Dashboard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/products') ? "active" : "" }}" href="{{route('products.index')}}">
                    <span data-feather="package"></span>
                    Product
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/orders') ? "active" : "" }}" href="{{route('admin.orders')}}">
                    <span data-feather="shopping-bag"></span>
                Orders
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/featured') ? "active" : "" }}" href="{{route('featured.product')}}">
                    <span data-feather="award"></span>
                    Featured Product
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/templateImages') ? "active" : "" }}" href="{{route('templateImages.index')}}">
                    <span data-feather="clipboard"></span>
                    Template
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/categories') ? "active" : "" }}" href="{{route('categories.index')}}">
                    <span data-feather="grid"></span>
                    Category
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Request::is('admin/tags') ? "active" : "" }}" href="{{route('tags.index')}}">
                    <span data-feather="tag"></span>
                    Tag
                </a>
            </li>

        </ul>
    </div>
</nav>