routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test', 'PageController@getTest')->name('test');

Route::get('/', 'PageController@getHome')->name('homePage');
Route::post('/newsletter', 'PageController@storeNewsletter')->name('newsletter');

Route::get('/help', 'PageController@getHowTo')->name('howToPage');
Route::get('/productShop/{tag?}', 'PageController@getProducts')->name('productsPage');
Route::get('/about', 'PageController@getAbout')->name('aboutPage');
Route::get('/terms', 'PageController@getTerms')->name('termsPage');
Route::get('/policy', 'PageController@getPolicy')->name('policyPage');

//Route::get('/contact', 'PageController@getContact')->name('contactPage');
Route::get('contact', 'ContactController@show')->name('contact.show');
Route::post('contact','ContactController@create')->name('contact.create');

Route::get('/profile/{user}', 'UserProfileController@showProfile')->name('user.profile');
Route::put('/profile/{user}', 'UserProfileController@updateUserProfile')->name('user.profile.update');
Route::put('/profileaddress/{user}', 'UserProfileController@updateUserAddress')->name('user.address.update');
Route::put('/profilepassword/{user}', 'UserProfileController@updateUserPassword')->name('user.password.update');

Route::get('/orderHistory', 'OrderController@index')->name('order.index');
Route::post('/order', 'OrderController@store')->name('order.store');

//socialite routes
//Route::get('login/google', 'Auth\LoginController@redirectToProvider')->name('googleLogin');
//Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/editor/{product?}', 'PageController@editor')->name('editorPage');
Route::get('searchResult', 'PageController@getSearchProduct')->name('productSearch');
Route::post('/preview', 'PageController@editorPreview')->name('editorPreview');

Route::middleware('role:admin')->prefix('admin')->group(function () {
    Route::group(['middleware' => 'auth'], function () {
        Route::get('/dashboard', 'AdminController@getDashboard')->name('admin.dashboard');

        Route::resource('categories', 'CategoryController');
        Route::resource('tags', 'TagController');
        Route::resource('products', 'ProductController');
        Route::resource('templateImages', 'TemplateImageController');

        Route::get('/orders', 'AdminOrderController@getOrders')->name('admin.orders');
        Route::get('/orders/{customerOrder}', 'AdminOrderController@updateOrderStatus')->name('admin.orders.update');
        Route::get('/items/{customerOrder}', 'AdminOrderController@viewOrderItems')->name('admin.order.items');

        Route::get('/featured', 'PageController@getFeaturedProduct')->name('featured.product');
        Route::get('/featured/{product}', 'PageController@removeFeaturedProduct')->name('update.featured.product');
    });
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/myCart', 'CartController@index')->name('cart.index');
    Route::post('/myCart/{product}', 'CartController@store')->name('cart.store');
    Route::delete('/myCart/{cartitem}', 'CartController@delete')->name('cart.destroy');
    Route::put('/myCart/{cartitem}', 'CartController@update')->name('cart.update');
});

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\CustomerOrder;
use App\OrderItem;
use App\User;
use Illuminate\Http\Request;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;

class OrderController extends Controller
{
    public function index()
    {
        $customerOrders = auth()->user()->customerOrders()->with('orderItems')->orderBy('created_at', 'desc')->get();
//        $customerOrders = auth()->user()->customerOrders()->with('orderItems')->with('product')->get();
//        $product = $customerOrders->with('product')->get();

        return view('profile.orderHistory', compact('customerOrders'));
    }

    public function store(Request $request, User $user)
    {
//        dd(auth()->user());
//        dd(auth()->user()->address);
        if (auth()->user()->address) {
            DB::transaction(function () use ($request, $user) {
                $orderitems = Cart::content();
                $finalPrice = Cart::subtotal();

                $customerorderdata = [
                    'user_id' => auth()->user()->id,
                    'charge' => $finalPrice,
                    'slug' => str_slug(str_limit(auth()->user()->name, 3, '')) . date('Ymdhis'),
                    'status' => 'On Process',

                ];
                $orderdata = [];
                $order = CustomerOrder::create($customerorderdata);
                foreach ($orderitems as $orderitem) {
                    $file = $orderitem->options->imageURI;
//                $file = base64_decode($file);
                    $name = $orderitem->name;
                    $filename = $name . '-' . time() . mt_rand() . '.png';
                    if ($file) {
//                    Storage::disk('public')->put($filename, $file);
                        Storage::disk('public')->put($filename, base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $file)));

                        array_push($orderdata, [
                            'order_id' => $order->id,
                            'product_id' => $orderitem->options->product_id,
                            'name' => $orderitem->name,
                            'price' => $orderitem->price,
                            'quantity' => $orderitem->qty,
//                    'imageURI' => $orderitem->options->imageURI,

//                        'imageURI' => $path,
                            'imageURI' => Storage::url($filename)
                        ]);
                    }
                }



                $order->orderItems()->insert($orderdata);

                $orderEmailData = [
                    'email' => auth()->user()->email,
                    'name'=>auth()->user()->name,
                    'ordernumber'=>count($orderdata),
                    'subject'=>'New order'
                ];

//                Mail::send('contact.orderEmail', $orderEmailData, function($message) use ($orderEmailData){
//                    $message->from($orderEmailData['email']);
//                    $message->to('roshitshrestha@gmail.com');
//                    $message->subject($orderEmailData['subject']);
//                });
            });
            Cart::destroy();


            return redirect()->route('order.index');
        } else {
            return redirect()->route('user.profile', auth()->user()->id)->with('addressCheck', 'Please add address.');
        }
    }
}


//$file = $request->file('image');
//$file = $orderitem->options->imageURI;
//$name=$orderitem->name,
//$filename = $name.'-'.time();
//if($file) {
//    Storage::disk('local')->put($filename, $file);
//}
//
//'imageURI' => $filename->storeAs('customerImage', $filename, 'public'),

resources/views/admin/orders/index.blade.php
@extends('admin.layout.app')
@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Orders</h1>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover">
                        <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Customer Name</th>
                            <th>Address</th>
                            <th>Contact Number</th>
                            <th>Charge</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($orders as $order)
                            <tr>
                                <td>{{ $order->id }}</td>
                                <td>{{ $order->user->name }}</td>
                                {{--<td><a href="{{ route('categories.show', $order->id) }}">{{ $category->name }}</a></td>--}}
                                {{--<td>{{ $category->name }}</td>--}}
                                <td>{{ $order->user->address }}</td>
                                <td>{{ $order->user->phone }}</td>
                                <td>{{ $order->charge }}</td>
                                <td>{{ $order->status }}</td>
                                <td>
                                    <a href="{{route('admin.orders.update',$order->id)}}" type="button" class="btn btn-success">
                                        Completed
                                    </a>
                                    <a href="{{route('admin.order.items', $order->id)}}" type="button" class="btn btn-info">
                                        View More
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/orders/items.blade.php
@extends('admin.layout.app')
@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Order Items</h1>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover">
                        <thead class="thead-dark">
                        <tr>
                            <th>Product Code</th>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Image</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($items as $item)
                            <tr>
                                {{--<td>{{ $item->product_id }}</td>--}}
                                <td class="align-middle">{{ $item->product()->get()->first()->product_code }}</td>
                                <td class="align-middle">{{ $item->name }}</td>
                                <td class="align-middle">{{ $item->price }}</td>
                                <td class="align-middle">{{ $item->quantity }}</td>
                                <td>
                                    <img src="{{asset($item->imageURI)}}" class="table-image">
                                </td>
                                <td class="align-middle">
                                    <a href="{{ $item->imageURI }}" download="{{asset($item->imageURI)}}" class="btn btn-primary" type="button">
                                        Download
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection